#!/bin/sh
#
rm -rf /home/root/PIDS/a4m*
# Start A4M Pipes...
echo Starting A4M
json_write data a4m | socat - tcp:10.0.0.2:6078 | json_read > /dev/null &
echo $! > /home/root/PIDS/a4m_data
echo $!
sleep 1
json_write serial a4m 3 | socat - tcp:10.0.0.2:6081 | json_read > /dev/null &
echo $! > /home/root/PIDS/a4m_serial3
echo $!
sleep 1
echo done...
